"""
Utility helpers for the Prompt Essentials practical lab.

The helpers are deliberately small and readable. They support two classroom modes:
1. Live API mode when OPENAI_API_KEY is configured.
2. Safe fallback mode when the key is missing or the network fails.

This keeps the notebook runnable end-to-end during teaching while still showing
the exact code path used for real model calls.
"""

from __future__ import annotations

import json
import os
import textwrap
from dataclasses import dataclass
from typing import Any, Iterable, Optional

from dotenv import load_dotenv

try:
    from langchain_core.messages import HumanMessage, SystemMessage
    from langchain_openai import ChatOpenAI
except Exception:  # pragma: no cover - handled gracefully in notebooks
    HumanMessage = None  # type: ignore
    SystemMessage = None  # type: ignore
    ChatOpenAI = None  # type: ignore


DEFAULT_MODEL_NAME = "gpt-4o-mini"


@dataclass
class PromptRunResult:
    """Container for one prompt experiment result.

    Args:
        output: Text generated by the model or fallback simulator.
        live: True if the output came from an API call.
        ok: True if the call or fallback completed successfully.
        error: Optional error string when live execution fails.
        model_name: Model used or intended for the call.

    Returns:
        A structured object that notebooks can print and compare.
    """

    output: str
    live: bool
    ok: bool
    error: Optional[str]
    model_name: str


def load_settings() -> dict[str, str]:
    """Load .env values and return the settings used by the lab.

    Args:
        None.

    Returns:
        Dictionary containing model and tracing-related configuration.
    """

    load_dotenv()
    settings = {
        "OPENAI_API_KEY": os.getenv("OPENAI_API_KEY", ""),
        "OPENAI_MODEL": os.getenv("OPENAI_MODEL", DEFAULT_MODEL_NAME),
        "LANGSMITH_TRACING": os.getenv("LANGSMITH_TRACING", os.getenv("LANGCHAIN_TRACING_V2", "false")),
        "LANGSMITH_API_KEY": os.getenv("LANGSMITH_API_KEY", os.getenv("LANGCHAIN_API_KEY", "")),
        "LANGSMITH_PROJECT": os.getenv("LANGSMITH_PROJECT", os.getenv("LANGCHAIN_PROJECT", "BIA_Prompt_Essentials")),
    }

    # Keep newer LangSmith variable names available to LangChain even if the
    # trainer uses legacy LANGCHAIN_* names from older material.
    if settings["LANGSMITH_TRACING"]:
        os.environ["LANGSMITH_TRACING"] = settings["LANGSMITH_TRACING"]
    if settings["LANGSMITH_API_KEY"]:
        os.environ["LANGSMITH_API_KEY"] = settings["LANGSMITH_API_KEY"]
    if settings["LANGSMITH_PROJECT"]:
        os.environ["LANGSMITH_PROJECT"] = settings["LANGSMITH_PROJECT"]

    return settings


def print_environment_status(settings: dict[str, str]) -> None:
    """Print a friendly readiness check for the notebook.

    Args:
        settings: Dictionary returned by load_settings().

    Returns:
        None. Prints setup status.
    """

    print("Environment check")
    print("-----------------")
    print(f"Model: {settings['OPENAI_MODEL']}")

    if settings["OPENAI_API_KEY"]:
        print("OPENAI_API_KEY: found — live calls are enabled.")
    else:
        print("OPENAI_API_KEY: not found — notebook will use simulated fallback outputs.")

    tracing_enabled = str(settings["LANGSMITH_TRACING"]).lower() in {"1", "true", "yes"}
    if tracing_enabled and settings["LANGSMITH_API_KEY"]:
        print(f"LangSmith tracing: enabled → project '{settings['LANGSMITH_PROJECT']}'.")
    elif tracing_enabled:
        print("LangSmith tracing: requested, but LANGSMITH_API_KEY is missing.")
    else:
        print("LangSmith tracing: disabled. Set LANGSMITH_TRACING=true to enable.")


def build_chat_model(
    *,
    temperature: float = 0.2,
    top_p: float = 0.95,
    model_name: Optional[str] = None,
) -> Any:
    """Create a LangChain ChatOpenAI model instance.

    Args:
        temperature: Controls randomness. Lower is more deterministic.
        top_p: Nucleus sampling value. Usually tune this or temperature, not both.
        model_name: Optional explicit model name. Defaults to OPENAI_MODEL.

    Returns:
        Configured ChatOpenAI instance.

    Raises:
        RuntimeError: If dependencies or API key are missing.
    """

    if ChatOpenAI is None:
        raise RuntimeError(
            "LangChain OpenAI packages are not installed. Run: pip install -r requirements.txt"
        )

    settings = load_settings()
    if not settings["OPENAI_API_KEY"]:
        raise RuntimeError("OPENAI_API_KEY is missing. Live calls are disabled.")

    return ChatOpenAI(
        model=model_name or settings["OPENAI_MODEL"],
        temperature=temperature,
        top_p=top_p,
    )


def normalize_content(content: Any) -> str:
    """Convert a LangChain model response content object into readable text.

    Args:
        content: The content returned by a chat model.

    Returns:
        Plain text representation of the content.
    """

    if isinstance(content, str):
        return content

    if isinstance(content, list):
        parts: list[str] = []
        for item in content:
            if isinstance(item, dict) and "text" in item:
                parts.append(str(item["text"]))
            else:
                parts.append(str(item))
        return "\n".join(parts)

    return str(content)


def invoke_messages(
    messages: list[Any],
    *,
    temperature: float = 0.2,
    top_p: float = 0.95,
    fallback_label: str = "default",
    run_name: Optional[str] = None,
) -> PromptRunResult:
    """Invoke the model with chat messages, falling back safely when needed.

    Args:
        messages: List of LangChain chat messages.
        temperature: Sampling temperature for live calls.
        top_p: Nucleus sampling parameter for live calls.
        fallback_label: Key used to select an educational fallback output.
        run_name: Optional LangSmith run name shown in traces.

    Returns:
        PromptRunResult with output and execution metadata.
    """

    settings = load_settings()
    model_name = settings["OPENAI_MODEL"]

    if not settings["OPENAI_API_KEY"]:
        return PromptRunResult(
            output=simulated_output(fallback_label),
            live=False,
            ok=True,
            error=None,
            model_name=model_name,
        )

    try:
        model = build_chat_model(temperature=temperature, top_p=top_p, model_name=model_name)
        config = {"run_name": run_name} if run_name else None
        response = model.invoke(messages, config=config)
        return PromptRunResult(
            output=normalize_content(response.content),
            live=True,
            ok=True,
            error=None,
            model_name=model_name,
        )
    except Exception as exc:
        return PromptRunResult(
            output=simulated_output(fallback_label),
            live=False,
            ok=False,
            error=str(exc),
            model_name=model_name,
        )


def make_messages(system: str, user: str) -> list[Any]:
    """Create system and user messages in LangChain format.

    Args:
        system: System instruction text.
        user: User task text.

    Returns:
        List containing a SystemMessage and HumanMessage.
    """

    if SystemMessage is None or HumanMessage is None:
        return [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]

    return [SystemMessage(content=system), HumanMessage(content=user)]


def pretty_print(title: str, text: str, width: int = 100) -> None:
    """Print a title and wrapped text block.

    Args:
        title: Heading shown before the text.
        text: Content to display.
        width: Maximum wrapping width.

    Returns:
        None. Prints formatted text.
    """

    print(f"\n{title}")
    print("=" * len(title))
    print(textwrap.fill(text, width=width, replace_whitespace=False))


def print_prompt(messages: Iterable[Any]) -> None:
    """Print chat messages in a readable role/content format.

    Args:
        messages: Iterable of LangChain message objects or dictionaries.

    Returns:
        None. Prints each message.
    """

    print("\nPrompt sent to the model")
    print("------------------------")
    for message in messages:
        role = getattr(message, "type", None) or getattr(message, "role", None)
        content = getattr(message, "content", None)
        if isinstance(message, dict):
            role = message.get("role", "message")
            content = message.get("content", "")
        print(f"\n[{str(role).upper()}]\n{content}")


def try_parse_json(text: str) -> tuple[bool, Any]:
    """Attempt to parse JSON from a model output.

    Args:
        text: Model output text.

    Returns:
        Tuple of (success flag, parsed object or error message).
    """

    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        cleaned = cleaned.replace("json\n", "", 1).strip()

    try:
        return True, json.loads(cleaned)
    except json.JSONDecodeError as exc:
        return False, f"JSON parsing failed: {exc}"


def has_required_keys(data: Any, required_keys: set[str]) -> tuple[bool, str]:
    """Check whether a parsed JSON object contains required top-level keys.

    Args:
        data: Parsed JSON object.
        required_keys: Keys expected in the object.

    Returns:
        Tuple containing pass/fail and a short explanation.
    """

    if not isinstance(data, dict):
        return False, "Parsed output is not a JSON object."

    missing = required_keys - set(data.keys())
    if missing:
        return False, f"Missing required keys: {sorted(missing)}"

    return True, "All required keys are present."


def estimate_demo_cost_usd(
    *,
    approximate_input_tokens: int,
    approximate_output_tokens: int,
    input_price_per_million: float = 0.15,
    output_price_per_million: float = 0.60,
) -> float:
    """Estimate API cost for a short text-only GPT-4o mini demo.

    Args:
        approximate_input_tokens: Estimated input tokens.
        approximate_output_tokens: Estimated output tokens.
        input_price_per_million: Input token price per 1M tokens.
        output_price_per_million: Output token price per 1M tokens.

    Returns:
        Estimated cost in USD.
    """

    input_cost = approximate_input_tokens / 1_000_000 * input_price_per_million
    output_cost = approximate_output_tokens / 1_000_000 * output_price_per_million
    return round(input_cost + output_cost, 4)


def simulated_output(label: str) -> str:
    """Return a realistic fallback output for classroom continuity.

    Args:
        label: Scenario key identifying which fallback to return.

    Returns:
        Simulated model output.
    """

    fallbacks = {
        "bad_summary": (
            "The customer is unhappy because the laptop is late and support has not resolved the issue."
        ),
        "better_summary": (
            "Issue: Delayed laptop delivery and repeated support failures.\n"
            "Customer impact: Cannot start a work project on time.\n"
            "Urgency: High.\n"
            "Recommended action: Escalate to logistics support, provide a delivery ETA, and offer a callback."
        ),
        "zero_shot": (
            "Category: Billing\nPriority: Medium\nReason: The user reports being charged twice and asks for a refund."
        ),
        "one_shot": (
            "{\n"
            '  "category": "Billing",\n'
            '  "priority": "Medium",\n'
            '  "reason": "The ticket reports a duplicate charge and refund request."\n'
            "}"
        ),
        "few_shot": (
            "{\n"
            '  "category": "Billing",\n'
            '  "priority": "High",\n'
            '  "reason": "The ticket combines duplicate payment with business impact and repeated failed support attempts."\n'
            "}"
        ),
        "temperature_low": (
            "Draft: Thank you for your patience. We are reviewing your delivery issue and will share an update shortly."
        ),
        "temperature_high": (
            "Draft: We know waiting on a delivery can derail your day. Our team is checking the route now and will come back with the clearest next step."
        ),
        "weak_system": (
            "Sure! I would recommend a 5-day Paris trip with flights, hotels, and sightseeing. It should be fun and affordable."
        ),
        "strong_system": (
            "{\n"
            '  "can_answer": false,\n'
            '  "missing_information": ["departure city", "travel dates", "budget", "traveller count"],\n'
            '  "safe_next_question": "Which city are you departing from, what dates are you considering, and what budget should I work within?",\n'
            '  "assumptions_made": []\n'
            "}"
        ),
        "template_ticket": (
            "{\n"
            '  "category": "Logistics",\n'
            '  "priority": "High",\n'
            '  "customer_impact": "Work project delayed because the replacement laptop has not arrived.",\n'
            '  "next_action": "Escalate to logistics, confirm replacement shipment status, and send an ETA to the customer."\n'
            "}"
        ),
        "debug_bad": (
            "A Bali beach trip in August is perfect. Book budget flights and enjoy sunny weather."
        ),
        "debug_better": (
            "{\n"
            '  "answer_status": "needs_clarification",\n'
            '  "risk_flags": ["weather may be seasonal", "budget not specified", "departure city missing"],\n'
            '  "clarifying_questions": ["Which city are you flying from?", "What is your budget range?", "Are your dates flexible?"],\n'
            '  "safe_response": "I can help shortlist beach options, but I should not invent live weather or flight prices without a source."\n'
            "}"
        ),
        "integration": (
            "{\n"
            '  "prompt_version": "travel_planner_v2",\n'
            '  "result_quality": "usable",\n'
            '  "format_valid": true,\n'
            '  "trace_hint": "Inspect the LangSmith run to compare input prompt, output format, latency, and token usage."\n'
            "}"
        ),
    }
    return fallbacks.get(label, "Simulated response: configure OPENAI_API_KEY for live model output.")
